// Item dataset loader. Uses the comprehensive wiki-sourced dataset
// (generated by scripts/build-data.ts → npm run build:data). The hand-verified
// items.seed.json remains as a small reference/fallback used by tests.
import { validateItems } from '../engine/items.schema';
import { Item } from '../engine/types';
import generated from './items.generated.json';

const baseItems = validateItems(generated);

// Sturgeon's roe becomes Caviar; every other fish produces ordinary Roe (→ Aged Roe).
const makesCaviar = (f: Item) => f.id === 'sturgeon' || f.tags.includes('caviar');

// Roe is its own searchable item, derived per fish: a Fish Pond stocked with a fish
// passively produces Roe worth 30 + ⌊fish price ÷ 2⌋ (wiki /Roe). Kept separate from the
// fish so "what to do with this fish" (sell/smoke) isn't mixed with pond roe.
const roeItems: Item[] = baseItems
  .filter((i) => i.category === 'fish')
  .map((f): Item => ({
    id: makesCaviar(f) ? 'sturgeon_roe' : `${f.id}_roe`,
    nameEn: makesCaviar(f) ? 'Sturgeon Roe' : `${f.nameEn} Roe`,
    nameZh: makesCaviar(f) ? '鲟鱼籽' : `${f.nameZh}鱼籽`,
    basePrice: 30 + Math.floor(f.basePrice / 2),
    category: 'roe',
    tags: makesCaviar(f) ? ['sturgeon_roe'] : [],
    source: f.source,
  }));

export const ITEMS: Item[] = [...baseItems, ...roeItems];

export const findItem = (id: string) => ITEMS.find((i) => i.id === id);
