// Item dataset loader. Uses the comprehensive wiki-sourced dataset
// (generated by scripts/build-data.ts → npm run build:data). The hand-verified
// items.seed.json remains as a small reference/fallback used by tests.
import { validateItems } from '../engine/items.schema';
import generated from './items.generated.json';

export const ITEMS = validateItems(generated);

export const findItem = (id: string) => ITEMS.find((i) => i.id === id);
